prefix = "miao"

[grpc]
name = "user"
listenOn = "127.0.0.1:8081"

[http]
listenOn = "127.0.0.1:8080"

[etcd]
hosts = ["127.0.0.1:2379"]
key = "user"

[mysql]
# etcd 默认mysql
key = "mysql-master"

# 自定义
username = ""
password = ""
address = ""
database = ""
other = ""

dsn = ""

[mysql-slave]
# etcd 默认mysql
key = "mysql-slave"

# 自定义
username = ""
password = ""
address = ""
database = ""
other = ""

dsn = ""

[traefik]
provider = "etcd"